"""Snap shapes that were *meant* to be geometric back onto their ideal form.

This is the one part of the pipeline that is opinion rather than measurement, so
it is opt-in.  An app-icon container drawn by hand (or generated by a model) is
often a couple of pixels out of true - different corner radii top and bottom,
say.  Tracing faithfully preserves the error; snapping removes it and makes the
pixel diff *worse* while making the logo better.  You have to choose.
"""

from __future__ import annotations

import math
from typing import List, Optional, Tuple

import numpy as np

from .config import Config
from .curves import fmt


def _corner_radii(mask: np.ndarray) -> Optional[Tuple[List[float], Tuple[int, int, int, int]]]:
    ys, xs = np.nonzero(mask)
    if len(xs) == 0:
        return None
    x0, x1, y0, y1 = int(xs.min()), int(xs.max()), int(ys.min()), int(ys.max())

    def run(line: np.ndarray) -> Optional[Tuple[int, int]]:
        idx = np.flatnonzero(line)
        return (int(idx[0]), int(idx[-1])) if len(idx) else None

    top, bot = run(mask[y0]), run(mask[y1])
    lft, rgt = run(mask[:, x0]), run(mask[:, x1])
    if not all((top, bot, lft, rgt)):
        return None
    tl = ((top[0] - x0) + (lft[0] - y0)) / 2.0
    tr = ((x1 - top[1]) + (rgt[0] - y0)) / 2.0
    br = ((x1 - bot[1]) + (y1 - rgt[1])) / 2.0
    bl = ((bot[0] - x0) + (y1 - lft[1])) / 2.0
    return [tl, tr, br, bl], (x0, y0, x1, y1)


def _consensus(radii: List[float], tol: float = 0.08) -> Tuple[float, List[int]]:
    """Largest group of corners that agree; ties go to the bigger radius."""
    best: Tuple[int, float, List[int]] = (0, -1.0, [])
    for r in radii:
        idx = [i for i, q in enumerate(radii) if abs(q - r) <= tol * max(r, 1.0)]
        mean = float(np.mean([radii[i] for i in idx]))
        if (len(idx), mean) > (best[0], best[1]):
            best = (len(idx), mean, idx)
    return best[1], best[2]


def _exponent(mask: np.ndarray, box, r: float, which: List[int]) -> float:
    """Recover the superellipse exponent from how full the corner runs.

    Only the corners that agreed on the radius get a vote.  Measuring an
    off-radius corner against the consensus radius reads as a different
    exponent, and a couple of those drag the fit badly.
    """
    x0, y0, x1, y1 = box
    hits = []
    corners = ((x0, y0, 1, 1), (x1, y0, -1, 1), (x1, y1, -1, -1), (x0, y1, 1, -1))
    for i, (cx, cy, sx, sy) in enumerate(corners):
        if i not in which:
            continue
        for t in range(1, int(r)):
            x, y = cx + sx * t, cy + sy * t
            if 0 <= y < mask.shape[0] and 0 <= x < mask.shape[1] and mask[y, x]:
                hits.append(float(t))
                break
    if not hits:
        return 2.0
    d = float(np.median(hits))
    ratio = 1.0 - d / r
    if not (0.05 < ratio < 0.95):
        return 2.0
    return -math.log(2.0) / math.log(ratio)


def _fit_controls(n: float) -> Tuple[float, float]:
    """Two cubics per corner, fitted to the superellipse. Offsets are fractions of R."""
    def sy(x):
        u = 1.0 - x
        return 1.0 - (max(1.0 - u ** n, 0.0)) ** (1.0 / n)

    samp = [(i / 240.0, sy(i / 240.0)) for i in range(241)]
    d = 1.0 - 2.0 ** (-1.0 / n)

    def curve(a, c, steps=140):
        s = c / math.sqrt(2)
        p = ((1.0, 0.0), (1.0 - a, 0.0), (d + s, d - s), (d, d))
        pts = []
        for i in range(steps + 1):
            t = i / steps
            m = 1 - t
            pts.append((
                m ** 3 * p[0][0] + 3 * m * m * t * p[1][0] + 3 * m * t * t * p[2][0] + t ** 3 * p[3][0],
                m ** 3 * p[0][1] + 3 * m * m * t * p[1][1] + 3 * m * t * t * p[2][1] + t ** 3 * p[3][1],
            ))
        return pts + [(y, x) for x, y in reversed(pts)]

    def err(a, c):
        cu = curve(a, c)
        return sum(min((px - qx) ** 2 + (py - qy) ** 2 for qx, qy in cu) for px, py in samp)

    best = None
    for a in np.arange(0.05, 0.95, 0.05):
        for c in np.arange(0.05, 0.95, 0.05):
            e = err(a, c)
            if best is None or e < best[0]:
                best = (e, float(a), float(c))
    _, a0, c0 = best
    for a in np.arange(max(a0 - 0.05, 0.01), a0 + 0.051, 0.01):
        for c in np.arange(max(c0 - 0.05, 0.01), c0 + 0.051, 0.01):
            e = err(a, c)
            if e < best[0]:
                best = (e, float(a), float(c))
    return best[1], best[2]


def squircle_path(x0, y0, x1, y1, r, n, prec=1) -> str:
    a, c = _fit_controls(n)
    A, C = a * r, c * r
    s = C / math.sqrt(2)
    d = r * (1.0 - 2.0 ** (-1.0 / n))
    f = lambda v: fmt(v, prec)
    P = []

    def corner(cx, cy, sx, sy, horiz_first):
        dx, dy = d * sx, d * sy
        if horiz_first:
            P.append("C%s %s %s %s %s %s" % (
                f(cx + sx * (r - A)), f(cy),
                f(cx + dx + sx * s), f(cy + dy - sy * s),
                f(cx + dx), f(cy + dy)))
            P.append("C%s %s %s %s %s %s" % (
                f(cx + dx - sx * s), f(cy + dy + sy * s),
                f(cx), f(cy + sy * (r - A)),
                f(cx), f(cy + sy * r)))
        else:
            P.append("C%s %s %s %s %s %s" % (
                f(cx), f(cy + sy * (r - A)),
                f(cx + dx - sx * s), f(cy + dy + sy * s),
                f(cx + dx), f(cy + dy)))
            P.append("C%s %s %s %s %s %s" % (
                f(cx + dx + sx * s), f(cy + dy - sy * s),
                f(cx + sx * (r - A)), f(cy),
                f(cx + sx * r), f(cy)))

    out = ["M%s %s" % (f(x0 + r), f(y0)), "H%s" % f(x1 - r)]
    corner(x1, y0, -1, 1, True)
    out += P; P = []
    out.append("V%s" % f(y1 - r))
    corner(x1, y1, -1, -1, False)
    out += P; P = []
    out.append("H%s" % f(x0 + r))
    corner(x0, y1, 1, -1, True)
    out += P; P = []
    out.append("V%s" % f(y0 + r))
    corner(x0, y0, 1, 1, False)
    out += P
    out.append("Z")
    return "".join(out)


def container(mask: np.ndarray, w: int, h: int, cfg: Config) -> Tuple[Optional[str], str]:
    """Replace a near-rounded-rectangle silhouette with an exact one."""
    got = _corner_radii(mask)
    if got is None:
        return None, ""
    radii, box = got
    x0, y0, x1, y1 = box
    bw, bh = x1 - x0 + 1, y1 - y0 + 1
    if bw * bh < 0.70 * w * h:
        return None, ""
    if mask.sum() < 0.80 * bw * bh:
        return None, ""
    r, members = _consensus(radii)
    if r < 2 or r > 0.5 * min(bw, bh):
        return None, ""
    n = _exponent(mask, box, r, members)
    n = float(min(max(n, 1.05), 8.0))
    spread = (max(radii) - min(radii)) / max(r, 1.0)
    note = (
        "container snapped to a superellipse: r=%.0f, n=%.2f "
        "(measured corner radii %s, spread %.0f%%)"
        % (r, n, ", ".join("%.0f" % q for q in radii), 100 * spread)
    )
    return squircle_path(x0, y0, x1 + 1, y1 + 1, r, n, cfg.precision), note
